
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '2B4FA8FCC8A1DD6C228AA0C16113F8FA'
    
_lr_action_items = {'COMMA':([2,3,9,],[7,-6,11,]),'SEMICOLON':([2,3,9,10,13,],[8,-6,-7,12,-8,]),'VALUE':([0,1,7,8,11,12,],[3,3,9,-4,9,-5,]),'$end':([1,4,5,6,8,12,],[-2,-1,0,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'idffile':([0,],[5,]),'idfobjectlist':([0,1,],[4,6,]),'valuelist':([7,11,],[10,13,]),'objectname':([0,1,],[2,2,]),'idfobject':([0,1,],[1,1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> idffile","S'",1,None,None,None),
  ('idffile -> idfobjectlist','idffile',1,'p_idffile','parseidf.py',55),
  ('idfobjectlist -> idfobject','idfobjectlist',1,'p_idfobjectlist','parseidf.py',63),
  ('idfobjectlist -> idfobject idfobjectlist','idfobjectlist',2,'p_idfobjectlist_multiple','parseidf.py',67),
  ('idfobject -> objectname SEMICOLON','idfobject',2,'p_idfobject','parseidf.py',71),
  ('idfobject -> objectname COMMA valuelist SEMICOLON','idfobject',4,'p_idfobject_with_values','parseidf.py',75),
  ('objectname -> VALUE','objectname',1,'p_objectname','parseidf.py',79),
  ('valuelist -> VALUE','valuelist',1,'p_valuelist','parseidf.py',83),
  ('valuelist -> VALUE COMMA valuelist','valuelist',3,'p_valuelist_multiple','parseidf.py',87),
]
